/**
 * activity.js — File activity aggregation (Phase 6)
 *
 * Reads raw JSONL trace events and counts reads vs edits per file.
 * Used for local and cross-repo activity heatmaps.
 */

import fs from 'fs';
import path from 'path';
import { withFileLock } from './file-lock.js';

/**
 * Aggregate file access counts from JSONL trace files for a given period.
 *
 * @param {string} tracesDir - Path to .claude/traces/
 * @param {number} days - Number of days to look back
 * @returns {object[]} Array of { path, reads, edits, total } sorted desc
 */
export function aggregateFileActivity(tracesDir, days = 7) {
  if (!tracesDir || !fs.existsSync(tracesDir)) return [];

  const cutoff = new Date();
  cutoff.setDate(cutoff.getDate() - days);
  const cutoffStr = cutoff.toISOString().slice(0, 10);

  const fileCounts = {};

  const dateDirs = fs.readdirSync(tracesDir)
    .filter(d => /^\d{4}-\d{2}-\d{2}$/.test(d) && d >= cutoffStr)
    .sort();

  for (const dateDir of dateDirs) {
    const dirPath = path.join(tracesDir, dateDir);
    let stat;
    try { stat = fs.statSync(dirPath); } catch { continue; }
    if (!stat.isDirectory()) continue;

    const jsonlFiles = fs.readdirSync(dirPath).filter(f => f.endsWith('.jsonl'));
    for (const jf of jsonlFiles) {
      let content;
      try { content = fs.readFileSync(path.join(dirPath, jf), 'utf8'); } catch { continue; }
      for (const line of content.split('\n')) {
        if (!line.trim()) continue;
        try {
          const event = JSON.parse(line);
          const files = event.files_touched || [];
          const tool = event.tool;

          for (const filePath of files) {
            if (!filePath) continue;
            if (!fileCounts[filePath]) fileCounts[filePath] = { reads: 0, edits: 0 };

            if (tool === 'Read' || tool === 'Grep' || tool === 'Glob') {
              fileCounts[filePath].reads++;
            } else if (tool === 'Edit' || tool === 'Write') {
              fileCounts[filePath].edits++;
            }
          }
        } catch { /* skip malformed line */ }
      }
    }
  }

  return Object.entries(fileCounts)
    .map(([filePath, counts]) => ({
      path: filePath,
      reads: counts.reads,
      edits: counts.edits,
      total: counts.reads + counts.edits,
    }))
    .sort((a, b) => b.total - a.total);
}

/**
 * Write file-activity.yaml from aggregated data.
 */
export function writeFileActivity(activityFile, activity, days = 7) {
  const today = new Date().toISOString().slice(0, 10);
  const periodStart = new Date(Date.now() - days * 86400000).toISOString().slice(0, 10);

  const lines = [
    '# File Activity — auto-generated by daily analysis',
    `period_start: ${periodStart}`,
    `period_end: ${today}`,
    `total_files: ${activity.length}`,
    '',
    'files:',
  ];

  for (const entry of activity.slice(0, 50)) {
    lines.push(`  - path: ${entry.path}`);
    lines.push(`    reads: ${entry.reads}`);
    lines.push(`    edits: ${entry.edits}`);
  }

  fs.mkdirSync(path.dirname(activityFile), { recursive: true });
  withFileLock(activityFile, () => {
    fs.writeFileSync(activityFile, lines.join('\n') + '\n', 'utf8');
  });
}

/**
 * Read file-activity.yaml into an array.
 */
export function readFileActivity(activityFile) {
  if (!fs.existsSync(activityFile)) return [];

  const content = fs.readFileSync(activityFile, 'utf8');
  const files = [];
  let current = null;

  for (const line of content.split('\n')) {
    if (/^\s{2}- path:\s*(.+)/.test(line)) {
      if (current) files.push(current);
      current = { path: line.match(/path:\s*(.+)/)[1].trim(), reads: 0, edits: 0 };
    } else if (current && /^\s{4}reads:\s*(\d+)/.test(line)) {
      current.reads = parseInt(line.match(/reads:\s*(\d+)/)[1], 10);
    } else if (current && /^\s{4}edits:\s*(\d+)/.test(line)) {
      current.edits = parseInt(line.match(/edits:\s*(\d+)/)[1], 10);
    }
  }
  if (current) files.push(current);
  return files;
}
