#!/usr/bin/env node
// Harness Harness — Smart Context Assembler (UserPromptSubmit hook)
// Auto-generated by harness-harness init. Do not edit manually.
//
// Single-writer: this hook both assembles context AND emits the fallback
// banner when assembly fails. It replaces the separate assembler-fallback.sh
// hook, whose stale-marker check ran in parallel with this process on the
// same event and raced the marker write, firing spurious banners on prompts
// where the assembler had in fact produced output.
//
// Dynamic imports only: this file may land in CommonJS projects.

(async () => {
  const fs = (await import('fs')).default;
  const path = (await import('path')).default;
  const { execFileSync } = await import('child_process');
  const { randomBytes } = await import('crypto');

  const projectDir = process.env.CLAUDE_PROJECT_DIR || process.cwd();
  const ASSEMBLER_SRC = '__ASSEMBLER_SRC__';

  // Stdin is read lazily and at most once: the native assembler reads
  // /dev/stdin itself, so the wrapper must not consume it on that path.
  let stdinCache = null;
  function readStdinOnce() {
    if (stdinCache === null) {
      try { stdinCache = fs.readFileSync(0, 'utf8'); } catch { stdinCache = ''; }
    }
    return stdinCache;
  }

  function sessionId() {
    try { return JSON.parse(stdinCache || '{}').session_id || 'unknown'; } catch { return 'unknown'; }
  }

  // Mirrors templates/hooks/lib/event-log.sh semantics. Non-fatal by contract.
  function logEvent(phase, extra) {
    try {
      const file = path.join(projectDir, '.harness', 'local', 'events.ndjson');
      fs.mkdirSync(path.dirname(file), { recursive: true });
      fs.appendFileSync(file, JSON.stringify({
        ts: new Date().toISOString(),
        event_id: `evt_${randomBytes(8).toString('hex')}`,
        hook: 'UserPromptSubmit',
        handler: 'hh-assembler.js',
        phase,
        exit_code: 0,
        session_id: sessionId(),
        extra,
      }) + '\n');
    } catch { /* non-fatal */ }
  }

  function delegatePath() {
    // Phase 9: assembler.delegate — let projects with their own assembler take
    // over context production. Configure in .harness/config.json:
    //   { "assembler": { "delegate": "scripts/my-assembler.js" } }
    try {
      const cfgPath = path.join(projectDir, '.harness', 'config.json');
      if (!fs.existsSync(cfgPath)) return null;
      const cfg = JSON.parse(fs.readFileSync(cfgPath, 'utf8'));
      return cfg?.assembler?.delegate ?? null;
    } catch { return null; }
  }

  function emitFallback(failures) {
    logEvent('error', { reason: 'context assembly failed; injecting fallback', failures });
    process.stdout.write(`<rules-reminder>
Context assembly failed for this prompt — no route context was injected.
Cause: ${failures.join('; ')}.
This banner is emitted by hh-assembler.js itself after its own run failed
(single process — not a stale-marker heuristic), so it reflects a real failure.
Reproduce: echo '{"prompt":"debug","session_id":"debug"}' | node .claude/hooks/hh-assembler.js
Details: .harness/local/events.ndjson (handler "hh-assembler.js", phase "error").
</rules-reminder>
`);
  }

  function tryDelegate(failures) {
    const delegate = delegatePath();
    if (!delegate) return false;
    const abs = path.isAbsolute(delegate) ? delegate : path.join(projectDir, delegate);
    try {
      const out = execFileSync('node', [abs], { input: readStdinOnce(), env: process.env });
      if (!out.toString().trim()) {
        failures.push(`delegate ${delegate} exited 0 but produced no output`);
        return false;
      }
      process.stdout.write(out);
      logEvent('end', { reason: 'delegate assembled context', delegate });
      return true;
    } catch (err) {
      failures.push(`delegate ${delegate} failed: ${err.message}`);
      return false;
    }
  }

  async function loadAssembler() {
    // Strategy 1: installed as npm dependency or globally
    try { return await import('harness-harness/assembler'); } catch { /* try next */ }
    // Strategy 2: absolute path to package (resolved at init time)
    try { return await import(ASSEMBLER_SRC); } catch { /* fall through */ }
    return null;
  }

  const failures = [];
  const hadDelegate = delegatePath() !== null;
  if (tryDelegate(failures)) return;
  if (hadDelegate) {
    // The delegate consumed stdin; the native assembler re-reads /dev/stdin,
    // would see EOF, and exits silently — a dead retry. Fall back directly.
    emitFallback(failures);
    return;
  }
  const m = await loadAssembler();
  if (!m) {
    failures.push('native assembler not importable (npm package and baked path both failed)');
    emitFallback(failures);
    return;
  }
  try {
    await m.main(projectDir);
  } catch (err) {
    failures.push(`native assembler threw: ${err.message}`);
    emitFallback(failures);
  }
})().catch(() => process.exit(1));
