/**
 * init command — Scaffold Harness Harness into a project
 *
 * Creates:
 *   .harness/
 *     config.json         — harness configuration
 *     routes/             — intent route configs (from templates)
 *     memory/             — effectiveness scores, overrides, patterns
 *     sessions/           — session state directories
 *   .claude/
 *     hooks/              — trace-capture, session-summary, state-nudge, assembler-fallback
 *     settings.json       — updated with hook entries (merged, not overwritten)
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { resolvePaths } from '../lib/paths.js';

const __filename = fileURLToPath(import.meta.url);
const TEMPLATES_DIR = path.resolve(path.dirname(__filename), '..', '..', 'templates');

export async function init(projectDir, flags) {
  const force = flags.includes('--force');
  const paths = resolvePaths(projectDir);

  console.log('');
  console.log('  Harness Harness — init');
  console.log(`  Project: ${projectDir}`);
  console.log('');

  // Check if already initialized
  if (fs.existsSync(paths.harnessDir) && !force) {
    console.log('  .harness/ already exists. Use --force to reinitialize.');
    console.log('  (This will NOT overwrite existing route configs or memory files.)');
    return;
  }

  // 1. Create directory structure
  const dirs = [
    paths.harnessDir,
    paths.routesDir,
    paths.memoryDir,
    paths.sessionsDir,
    path.join(paths.sessionsDir, 'archive'),
    paths.tracesDir,
    paths.hooksDir,
  ];

  for (const dir of dirs) {
    fs.mkdirSync(dir, { recursive: true });
  }
  console.log('  Created directory structure');

  // 2. Copy route templates (don't overwrite existing)
  const routeTemplates = fs.readdirSync(path.join(TEMPLATES_DIR, 'routes'));
  let routesCopied = 0;
  for (const tmpl of routeTemplates) {
    const dest = path.join(paths.routesDir, tmpl);
    if (!fs.existsSync(dest)) {
      fs.copyFileSync(path.join(TEMPLATES_DIR, 'routes', tmpl), dest);
      routesCopied++;
    }
  }
  console.log(`  Routes: ${routesCopied} templates installed (${routeTemplates.length - routesCopied} already exist)`);

  // 3. Install hooks with project path substitution
  const hookFiles = [
    { src: 'trace-capture.sh', dest: 'hh-trace-capture.sh' },
    { src: 'session-summary.js', dest: 'hh-session-summary.js' },
    { src: 'state-nudge.sh', dest: 'hh-state-nudge.sh' },
    { src: 'assembler-fallback.sh', dest: 'hh-assembler-fallback.sh' },
  ];

  for (const hook of hookFiles) {
    const srcContent = fs.readFileSync(path.join(TEMPLATES_DIR, 'hooks', hook.src), 'utf8');
    const content = srcContent.replace(/\{\{PROJECT_DIR\}\}/g, projectDir);
    const destPath = path.join(paths.hooksDir, hook.dest);
    fs.writeFileSync(destPath, content, 'utf8');
    // Make shell scripts executable
    if (hook.dest.endsWith('.sh')) {
      fs.chmodSync(destPath, 0o755);
    }
  }
  console.log(`  Hooks: ${hookFiles.length} installed to .claude/hooks/`);

  // 4. Install assembler script (the UserPromptSubmit hook)
  const assemblerSrc = path.resolve(path.dirname(__filename), '..', 'lib', 'context-assembler.js');
  const assemblerDest = path.join(paths.hooksDir, 'hh-assembler.js');

  // Create a thin wrapper that invokes the assembler with the project dir
  const assemblerWrapper = `#!/usr/bin/env node
// Harness Harness — Smart Context Assembler (UserPromptSubmit hook)
// Auto-generated by harness-harness init. Do not edit manually.
import { main } from '${assemblerSrc}';
main('${projectDir}').catch(() => process.exit(1));
`;
  fs.writeFileSync(assemblerDest, assemblerWrapper, 'utf8');
  console.log('  Assembler: installed as .claude/hooks/hh-assembler.js');

  // 5. Update .claude/settings.json (merge, don't overwrite)
  updateClaudeSettings(paths, projectDir);
  console.log('  Settings: .claude/settings.json updated with hook entries');

  // 6. Create harness config
  const configPath = paths.configFile;
  if (!fs.existsSync(configPath)) {
    const config = {
      version: '0.1.0',
      projectDir,
      budgetTokens: 130000,
      customIntents: [],
      fileToRules: {},
      retentionDays: 30,
    };
    fs.writeFileSync(configPath, JSON.stringify(config, null, 2), 'utf8');
    console.log('  Config: .harness/config.json created');
  }

  // 7. Create initial memory files
  const memoryFiles = [
    { path: paths.effectivenessFile, content: '## Harness Effectiveness Scores\n\nNo data yet. Scores will appear after your first analyzed session.\n' },
    { path: paths.overridesFile, content: '## Route Overrides\n\nNo proposals yet.\n' },
    { path: paths.tracePatternsFile, content: '# Trace Patterns\n\nSession stats will be appended here by the session-summary hook.\n' },
    { path: paths.workStatusFile, content: '## Work Status\n\nUpdate this file with your current work status.\n' },
  ];

  for (const mf of memoryFiles) {
    if (!fs.existsSync(mf.path)) {
      fs.writeFileSync(mf.path, mf.content, 'utf8');
    }
  }
  console.log('  Memory: initial files created');

  // 8. Create .gitignore for harness
  const gitignorePath = path.join(paths.harnessDir, '.gitignore');
  if (!fs.existsSync(gitignorePath)) {
    fs.writeFileSync(gitignorePath, [
      '# Harness Harness',
      'sessions/archive/',
      '',
    ].join('\n'));
  }

  console.log('');
  console.log('  Done! Harness Harness is ready.');
  console.log('');
  console.log('  Next steps:');
  console.log('    1. Edit .harness/routes/general.md with your project identity and rules');
  console.log('    2. Customize other routes in .harness/routes/ for your codebase');
  console.log('    3. Map your rule files to IDs in .harness/config.json (fileToRules)');
  console.log('    4. Start using Claude Code — the harness will begin tracing automatically');
  console.log('    5. After a few sessions, run: harness-harness health');
  console.log('');
}

function updateClaudeSettings(paths, projectDir) {
  let settings = {};

  if (fs.existsSync(paths.claudeSettingsFile)) {
    try {
      settings = JSON.parse(fs.readFileSync(paths.claudeSettingsFile, 'utf8'));
    } catch {
      settings = {};
    }
  }

  if (!settings.hooks) settings.hooks = {};

  // Define harness hooks
  const harnessHooks = {
    UserPromptSubmit: [
      {
        type: 'command',
        command: `node ${path.join(paths.hooksDir, 'hh-assembler.js')}`,
        timeout: 10000,
      },
      {
        type: 'command',
        command: `bash ${path.join(paths.hooksDir, 'hh-assembler-fallback.sh')}`,
        timeout: 5000,
      },
    ],
    PostToolUse: [
      {
        type: 'command',
        command: `bash ${path.join(paths.hooksDir, 'hh-trace-capture.sh')}`,
        timeout: 5000,
      },
    ],
    Stop: [
      {
        type: 'command',
        command: `node ${path.join(paths.hooksDir, 'hh-session-summary.js')}`,
        timeout: 30000,
      },
    ],
  };

  // Add state-nudge for Edit and Write tools
  const stateNudgeHook = {
    type: 'command',
    command: `bash ${path.join(paths.hooksDir, 'hh-state-nudge.sh')}`,
    timeout: 5000,
    matcher: {
      tool_name: ['Edit', 'Write'],
    },
  };

  // Merge hooks — add harness hooks without removing existing user hooks
  for (const [event, hooks] of Object.entries(harnessHooks)) {
    if (!settings.hooks[event]) settings.hooks[event] = [];

    // Remove any existing harness-harness hooks (for re-init)
    settings.hooks[event] = settings.hooks[event].filter(h =>
      !(h.command && h.command.includes('hh-'))
    );

    // Add harness hooks
    settings.hooks[event].push(...hooks);
  }

  // Add state-nudge to PostToolUse if not already present
  if (!settings.hooks.PostToolUse.some(h => h.command && h.command.includes('hh-state-nudge'))) {
    settings.hooks.PostToolUse.push(stateNudgeHook);
  }

  fs.mkdirSync(path.dirname(paths.claudeSettingsFile), { recursive: true });
  fs.writeFileSync(paths.claudeSettingsFile, JSON.stringify(settings, null, 2), 'utf8');
}
